### ISSUE TITLE
Update all CAPS information to use title case

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-wp#32]
### 💡 Description

For titles, facets, etc, we should change ALL CAPS to Title Case, unless explicitly identified via TBD config file

Example of a config we used in the old keyword search that we could turn into JSON: https://github.com/NASA-PDS/registry-legacy-solr/blob/main/registry-mgr-legacy/src/main/resources/collections/data/xslt/capitalize.xml

**Comment by jordanpadams** [comment]
@newcomber @anilnatha @eddiesarevalo something we can talk about next week if it makes sense to something like this.

**Comment by anilnatha** [comment]
Yes! The text I'm seeing isn't consistent and it would be nice if it was.  However, I don't think we can't apply this blanket rule because there are situations where things should be all caps, like when acronyms are using in an investigation or instrument title.

**Comment by jordanpadams** [comment]
Closing as won't fix for foreseeable future
