### ISSUE TITLE
Update routing configuration to support leading "/portal" folder in deployments

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/portal-wp#35]
### 💡 Description

Deployments of the portal codebase will be nested under a folder called "portal" in AWS. As such, our routing configuration needs to be updated to account for this change. In addition, routes that serve image assets may need to be fixed as well as updating proxy configuration for ongoing local development needs.

**Comment by jordanpadams** [comment]
closes https://github.com/NASA-PDS/portal-wp/pull/37
