### ISSUE TITLE
Any time a  `Stop Date` is encountered in design, update `3000-01-01T00:00:00Z` to be ongoing

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-wp#42]
### 💡 Description

Update `3000-01-01T00:00:00Z` to be ongoing

**Comment by anilnatha** [comment]
@jordanpadams I added the ability to check for the date `3000-01-01T00:00:00Z` and replace it with `ongoing`.

Closing this ticket as it's done.
