### ISSUE TITLE
Update Investigations on homepage

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-wp#67]
### 💡 Description

Right now we have 3 landers/rovers on the homepage, we need to diversify:

* Mars 2020
* LRO
* New Horizons / KEM2 (extended mission)
* Cassini
* MRO

**Comment by jordanpadams** [comment]
Status: Work starting. Should not be too difficult dependent upon images.

**Comment by tloubrieu-jpl** [comment]
Code is ready for a Pull Request.
