### ISSUE TITLE
Notify user of temporary database downtime when no results return from Solr search

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-wp#71]
### 💡 Description

When homepage or search page appears, immediately query current search to see if any data is in the system (rows=0 to make this as fast as possible). If 0 results come back or does not return 200, show a notification that "The PDS search database is undergoing system maintenance at this time. We apologize for the inconvenience. Check back in a few minutes." (or some better copy decided upon by the design team)

**Comment by jordanpadams** [comment]
@edwardbarraza can we get some copy here?

**Comment by edwardbarraza** [comment]
If this is a planned outage we should notify ahead of time using the HDS Banner. 

If it is not a planned outage we should notify using a site-wide banner anyway.

"**PDS Search is down for maintenance.** 
We expect it to be back shortly. Thanks for your patience."

We can also direct users to alternative approaches to search such as going through our directory pages. If Solr is down does that in any way affect the quality of data that we see on the Investigation/Instrument/etc pages?
