### ISSUE TITLE
Add sorting of Collections

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/portal-wp#86]
### 💡 Description

We received feedback that it isn't obvious to users what the sort order is of collections on the instrument's detail page.

Tasks
- [x] Sort the Processing Level groups by following the logical data pipeline order (i.e. raw -> partially processed -> calibrated)
- [x] Sort collections associated with a processing level in ascending (A-Z) order.

**Comment by tloubrieu-jpl** [comment]
@anilnatha is working on that now.
Same will be done in the investigation page.
