### ISSUE TITLE
Add Banner Message indicating "beta site"

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/portal-wp#90]
### 💡 Description

A banner message indicating that the user is viewing the "beta" of the new portal is needed.

Need to coordinate with design team on the style definitions for the banner.

**Comment by anilnatha** [comment]
Work is going smoothly, have the component mocked up.

<img width="1485" alt="image" src="https://github.com/user-attachments/assets/6da69d20-c561-48f9-81a8-e29350e7503a">

**Comment by tloubrieu-jpl** [comment]
Waiting for review from @edwardbarraza

**Comment by edwardbarraza** [comment]
I think so as long as we don't run in to a situation where the message itself is two rows, I think centered-aligned is fine.

**Comment by anilnatha** [comment]
@edwardbarraza This was my initial take on just getting the skeleton of the component integrated. The HDS styles are left aligned and do allow for multi-line support. They even allow for a link to be added; however we are forgoing on the ability to dismiss/hide the banner message.

Let me know what text you would like to include here to inform users that they are viewing the beta site and I'll add it in.

**Comment by anilnatha** [comment]
@edwardbarraza Here are updated screenshots of the working version of the banner component. Let's chat about this tomorrow. 

desktop:

<img width="1226" alt="image" src="https://github.com/user-attachments/assets/6e6b4494-3d22-4cc2-8b3a-4c9bd2c34077">

mobile/tablet:

<img width="530" alt="image" src="https://github.com/user-attachments/assets/43cbab05-2583-4a4b-b416-2200ae8d22d1">

**Comment by anilnatha** [comment]
@Edward Barraza From our conversation this morning, I made the adjustments we spoke of. I also updated my configuration so that multiple banners can be displayed simultaneously, when needed.  Attached is the updated example implementation.

Now I just need the final text we want to display for the "beta site" banner from you.

Here is an example implementation showing two banners:

![image](https://github.com/user-attachments/assets/137caf61-2534-4f58-9ea2-fe483e12138d)

![Screen Shot 2024-10-30 at 10 33 00](https://github.com/user-attachments/assets/dc32e99d-602a-4e36-810f-daa237af6b4a)

**Comment by edwardbarraza** [comment]
For Beta Message:

**PDS is in Beta** As we work on improving the site, please keep in mind that it is still under development and may have limitations. Feel free to send us feedback regarding your experience.

**Comment by anilnatha** [comment]
Final implementation example:

#### Desktop:

<img width="1601" alt="image" src="https://github.com/user-attachments/assets/ed3775cb-a232-474c-918c-572bf1bf4721">

#### Tablet:

<img width="856" alt="image" src="https://github.com/user-attachments/assets/03caa860-1ae8-4c5a-b1bd-a908d39bf4af">

#### Mobile:

<img width="585" alt="image" src="https://github.com/user-attachments/assets/03a89e60-bcc4-4a61-8990-f3a6299758df">
